name: flutter_max
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^3.1.0
  flutter_redux: ^0.5.3
  shared_preferences: ^0.5.3+3
  flutter_localizations:
    sdk: flutter
  flutter_webview_plugin: ^0.3.5
  fluttertoast: ^3.1.0
  url_launcher: ^5.0.5
  share: ^0.6.2
  http: 0.12.0+2
  dio: 2.1.13
  connectivity: 0.4.3+4
  event_bus: 1.1.0
  flutter_gallery_assets: 0.1.9+2
  image_picker: ^0.6.0+16


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.jpg
    - assets/images/user.png
    - assets/images/ic_comment.png
    - assets/images/ic_img_default.jpg
    - assets/images/01.jpg
    - assets/images/02.jpg
    - assets/images/03.jpg
    - assets/images/04.jpg
    - assets/images/05.jpg
    - assets/images/06.jpg
    - assets/images/07.jpg
    - assets/images/08.jpg
    - assets/images/09.jpg
    - assets/images/10.jpg
    - assets/images/11.jpg
    - assets/images/12.jpg
    - assets/images/13.jpg
    - assets/images/14.jpg
    - assets/images/15.jpg
    - assets/images/16.jpg
    - assets/images/17.jpg
    - assets/images/19.jpg
    - assets/images/20.jpg
    - assets/images/21.jpg
    - assets/images/22.jpg
    - assets/images/23.jpg
    - assets/images/24.jpg
    - assets/images/25.jpg
    - assets/images/26.jpg
    - assets/images/27.jpg
    - assets/images/28.jpg
    - assets/images/29.jpg
    - assets/images/30.jpg
    - assets/images/31.jpg
    - assets/images/32.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
